class_name TileAtlas
## Generated by tools/gen_tiles.py. Do not edit by hand: rerun the script.
## Where each tile sits in the per-band atlases under res://assets/sprites/tiles/.

const CELL: int = 24
const COLS: int = 8
const FLOOR_VARIANTS: int = 4
## One atlas per FloorTheme band, in band order.
const BANDS: Array[String] = ["path", "river", "gate", "palace"]
## Floor decor each band may scatter: [name, frame count].
const DECOR := {
	"path": [
		["bones", 1], ["skull", 1], ["crack", 1], ["pebbles", 1],
		["grass", 1], ["paper", 1], ["candle", 2],
	],
	"river": [
		["bones", 1], ["crack", 1], ["pebbles", 1], ["puddle", 1],
		["reeds", 1], ["lotus", 1], ["candle", 2],
	],
	"gate": [
		["bones", 1], ["skull", 1], ["crack", 1], ["chain", 1],
		["ember", 2], ["lava", 2], ["candle", 2],
	],
	"palace": [
		["crack", 1], ["coins", 1], ["cushion", 1], ["scroll", 1],
		["incense", 2], ["candle", 2],
	],
}
## Decor that casts a little warm light.
const LIGHTS: Array[String] = ["candle", "ember", "lava", "incense"]
const INDEX := {
	"floor_0": 0,
	"floor_1": 1,
	"floor_2": 2,
	"floor_3": 3,
	"wall_face_0": 4,
	"wall_face_1": 5,
	"wall_face_special": 6,
	"wall_top_0": 7,
	"wall_top_1": 8,
	"door": 9,
	"door_side": 10,
	"stairs": 11,
	"well_0": 12,
	"well_1": 13,
	"altar_0": 14,
	"altar_1": 15,
	"trap_spotted": 16,
	"trap_spent": 17,
	"decor_bones_0": 18,
	"decor_skull_0": 19,
	"decor_crack_0": 20,
	"decor_pebbles_0": 21,
	"decor_grass_0": 22,
	"decor_paper_0": 23,
	"decor_candle_0": 24,
	"decor_candle_1": 25,
	"decor_puddle_0": 26,
	"decor_reeds_0": 27,
	"decor_lotus_0": 28,
	"decor_chain_0": 29,
	"decor_ember_0": 30,
	"decor_ember_1": 31,
	"decor_lava_0": 32,
	"decor_lava_1": 33,
	"decor_coins_0": 34,
	"decor_cushion_0": 35,
	"decor_scroll_0": 36,
	"decor_incense_0": 37,
	"decor_incense_1": 38,
}

## The atlas region of a tile, in atlas pixels.
static func region(tile_name: String) -> Rect2:
	var i: int = INDEX.get(tile_name, 0)
	return Rect2((i % COLS) * CELL, (i / COLS) * CELL, CELL, CELL)
