extends Node
## Single-slot run save (roguelike checkpoint on every floor entry). The save
## is deleted when the run ends. Autoloaded as "SaveManager".

## Overridable so tests never touch the player's real save.
var save_path: String = "user://save.json"
const SAVE_VERSION: int = 1

func has_save() -> bool:
	return FileAccess.file_exists(save_path)

func delete_save() -> void:
	if has_save():
		DirAccess.remove_absolute(ProjectSettings.globalize_path(save_path))

func save_run(player: Player) -> void:
	var inv: Array = []
	for entry in GameState.inventory:
		inv.append({"id": entry.item_data.id, "qty": entry.quantity})
	var data: Dictionary = {
		"version": SAVE_VERSION,
		"class_id": GameState.player_class.id,
		"floor": GameState.current_floor,
		"hp": player.current_hp,
		"stats": {
			"max_hp": player.stats.max_hp,
			"attack_min": player.stats.attack_min,
			"attack_max": player.stats.attack_max,
			"defense": player.stats.defense,
			"accuracy": player.stats.accuracy,
			"evasion": player.stats.evasion,
		},
		"level": GameState.player_level,
		"xp": GameState.player_xp,
		"xp_next": GameState.player_xp_to_next,
		"gold": GameState.gold,
		"turns": GameState.turn_count,
		"skill_cd": GameState.skill_cooldown_left,
		"statuses": player.statuses.duplicate(),
		"weapon": GameState.equipped_weapon.id if GameState.equipped_weapon else "",
		"armor": GameState.equipped_armor.id if GameState.equipped_armor else "",
		"inventory": inv,
		"identified": GameState.identified_types.keys(),
	}
	var f := FileAccess.open(save_path, FileAccess.WRITE)
	if f == null:
		push_warning("SaveManager: cannot write %s (error %d)" % [save_path, FileAccess.get_open_error()])
		return
	f.store_string(JSON.stringify(data))

## Returns the parsed save, or {} if missing/corrupt/incompatible.
func load_data() -> Dictionary:
	if not has_save():
		return {}
	var f := FileAccess.open(save_path, FileAccess.READ)
	if f == null:
		return {}
	var parsed = JSON.parse_string(f.get_as_text())
	if typeof(parsed) != TYPE_DICTIONARY or int(parsed.get("version", 0)) != SAVE_VERSION:
		return {}
	return parsed

## Restores GameState and player stats from a save. The floor itself is
## regenerated by the caller.
func apply(data: Dictionary, player: Player) -> void:
	var s: Dictionary = data.stats
	player.stats.max_hp = int(s.max_hp)
	player.stats.attack_min = int(s.attack_min)
	player.stats.attack_max = int(s.attack_max)
	player.stats.defense = int(s.defense)
	player.stats.accuracy = int(s.accuracy)
	player.stats.evasion = int(s.evasion)
	player.current_hp = clampi(int(data.hp), 1, player.stats.max_hp)
	GameState.player_level = int(data.level)
	GameState.player_xp = int(data.xp)
	GameState.player_xp_to_next = int(data.xp_next)
	GameState.gold = int(data.gold)
	GameState.turn_count = int(data.turns)
	GameState.skill_cooldown_left = int(data.skill_cd)
	var saved_statuses = data.get("statuses", {})
	if typeof(saved_statuses) == TYPE_DICTIONARY:
		for key in saved_statuses.keys():
			player.apply_status(str(key), int(saved_statuses[key]))
	GameState.inventory.clear()
	for e in data.inventory:
		var item: ItemData = ItemDatabase.get_item(str(e.id))
		if item:
			for i in range(int(e.qty)):
				GameState.add_item(item)
	GameState.equipped_weapon = ItemDatabase.get_item(str(data.weapon)) if str(data.weapon) != "" else null
	GameState.equipped_armor = ItemDatabase.get_item(str(data.armor)) if str(data.armor) != "" else null
	GameState.identified_types.clear()
	for id in data.identified:
		GameState.identified_types[str(id)] = true
