extends Node
## Single-slot run save. Written on every floor entry, every few turns and
## when the app is backgrounded or closed, and it carries the current floor
## exactly as it stands, so continuing never rerolls the layout or undoes
## progress. The save is deleted when the run ends. Autoloaded as "SaveManager".

## Overridable so tests never touch the player's real save.
var save_path: String = "user://save.json"
const SAVE_VERSION: int = 1

func has_save() -> bool:
	return FileAccess.file_exists(save_path)

func delete_save() -> void:
	if has_save():
		DirAccess.remove_absolute(ProjectSettings.globalize_path(save_path))

func save_run(player: Player) -> void:
	var inv: Array = []
	for entry in GameState.inventory:
		inv.append({"id": entry.item_data.id, "qty": entry.quantity})
	var data: Dictionary = {
		"version": SAVE_VERSION,
		"class_id": GameState.player_class.id,
		"floor": GameState.current_floor,
		"hp": player.current_hp,
		"stats": {
			"max_hp": player.stats.max_hp,
			"attack_min": player.stats.attack_min,
			"attack_max": player.stats.attack_max,
			"defense": player.stats.defense,
			"accuracy": player.stats.accuracy,
			"evasion": player.stats.evasion,
		},
		"level": GameState.player_level,
		"xp": GameState.player_xp,
		"xp_next": GameState.player_xp_to_next,
		"gold": GameState.gold,
		"turns": GameState.turn_count,
		"skill_cd": GameState.skill_cooldown_left,
		"statuses": player.statuses.duplicate(),
		"weapon": GameState.equipped_weapon.id if GameState.equipped_weapon else "",
		"armor": GameState.equipped_armor.id if GameState.equipped_armor else "",
		"inventory": inv,
		"identified": GameState.identified_types.keys(),
		"killer": GameState.last_attacker,
		"dead": not player.is_alive,
		"floor_state": encode_floor(player),
	}
	var f := FileAccess.open(save_path, FileAccess.WRITE)
	if f == null:
		push_warning("SaveManager: cannot write %s (error %d)" % [save_path, FileAccess.get_open_error()])
		return
	f.store_string(JSON.stringify(data))

## Returns the parsed save, or {} if missing/corrupt/incompatible.
func load_data() -> Dictionary:
	if not has_save():
		return {}
	var f := FileAccess.open(save_path, FileAccess.READ)
	if f == null:
		return {}
	var parsed = JSON.parse_string(f.get_as_text())
	if typeof(parsed) != TYPE_DICTIONARY or int(parsed.get("version", 0)) != SAVE_VERSION:
		return {}
	return parsed

## Restores GameState and player stats from a save. The floor itself is
## regenerated by the caller.
func apply(data: Dictionary, player: Player) -> void:
	var s: Dictionary = data.stats
	player.stats.max_hp = int(s.max_hp)
	player.stats.attack_min = int(s.attack_min)
	player.stats.attack_max = int(s.attack_max)
	player.stats.defense = int(s.defense)
	player.stats.accuracy = int(s.accuracy)
	player.stats.evasion = int(s.evasion)
	player.current_hp = clampi(int(data.hp), 1, player.stats.max_hp)
	GameState.player_level = int(data.level)
	GameState.player_xp = int(data.xp)
	GameState.player_xp_to_next = int(data.xp_next)
	GameState.gold = int(data.gold)
	GameState.turn_count = int(data.turns)
	GameState.skill_cooldown_left = int(data.skill_cd)
	var saved_statuses = data.get("statuses", {})
	if typeof(saved_statuses) == TYPE_DICTIONARY:
		for key in saved_statuses.keys():
			player.apply_status(str(key), int(saved_statuses[key]))
	GameState.inventory.clear()
	for e in data.inventory:
		var item: ItemData = ItemDatabase.get_item(str(e.id))
		if item:
			for i in range(int(e.qty)):
				GameState.add_item(item)
	GameState.equipped_weapon = ItemDatabase.get_item(str(data.weapon)) if str(data.weapon) != "" else null
	GameState.equipped_armor = ItemDatabase.get_item(str(data.armor)) if str(data.armor) != "" else null
	GameState.identified_types.clear()
	for id in data.identified:
		GameState.identified_types[str(id)] = true
	GameState.last_attacker = str(data.get("killer", ""))

## The current floor as plain data: tiles and what the player has seen as one
## digit per cell, then ground loot, noticed traps and every living monster.
func encode_floor(player: Player) -> Dictionary:
	var rows: Array[String] = []
	var seen: Array[String] = []
	for y in range(DungeonState.height):
		var row := ""
		var seen_row := ""
		for x in range(DungeonState.width):
			var pos := Vector2i(x, y)
			row += str(DungeonState.tile_at(pos))
			seen_row += "1" if DungeonState.explored.has(pos) else "0"
		rows.append(row)
		seen.append(seen_row)
	var items: Array = []
	for pos in DungeonState.items_at.keys():
		items.append([pos.x, pos.y, DungeonState.items_at[pos].id])
	var gold: Array = []
	for pos in DungeonState.gold_at.keys():
		gold.append([pos.x, pos.y, DungeonState.gold_at[pos]])
	var spotted: Array = []
	for pos in DungeonState.spotted_traps.keys():
		spotted.append([pos.x, pos.y])
	var monsters: Array = []
	for m in TurnManager.monsters:
		if is_instance_valid(m) and m.is_alive:
			monsters.append({"id": m.data.id, "x": m.grid_pos.x, "y": m.grid_pos.y,
				"hp": m.current_hp, "summoned": m.has_summoned()})
	return {
		"w": DungeonState.width, "h": DungeonState.height, "rows": rows, "seen": seen,
		"stairs": [DungeonState.stairs_pos.x, DungeonState.stairs_pos.y],
		"player": [player.grid_pos.x, player.grid_pos.y],
		"items": items, "gold": gold, "spotted": spotted, "monsters": monsters,
	}

## Parses encode_floor output without touching any state. Returns {} if the
## snapshot is missing or damaged, so the caller can generate a fresh floor.
## Items or monsters whose ids no longer exist are dropped.
func decode_floor(state) -> Dictionary:
	if typeof(state) != TYPE_DICTIONARY:
		return {}
	var w: int = int(state.get("w", 0))
	var h: int = int(state.get("h", 0))
	var rows = state.get("rows")
	var seen = state.get("seen")
	if w <= 0 or h <= 0 or typeof(rows) != TYPE_ARRAY or typeof(seen) != TYPE_ARRAY or rows.size() != h or seen.size() != h:
		return {}
	var grid: Dictionary = {}
	var explored: Dictionary = {}
	for y in range(h):
		var row: String = str(rows[y])
		var seen_row: String = str(seen[y])
		if row.length() != w or seen_row.length() != w:
			return {}
		for x in range(w):
			var ch: String = row[x]
			if not ch.is_valid_int() or int(ch) >= DungeonState.Tile.size():
				return {}
			grid[Vector2i(x, y)] = int(ch)
			if seen_row[x] == "1":
				explored[Vector2i(x, y)] = true
	var player_pos: Vector2i = _vec(state.get("player"))
	var stairs: Vector2i = _vec(state.get("stairs"))
	if grid.get(player_pos, DungeonState.Tile.WALL) == DungeonState.Tile.WALL or not grid.has(stairs):
		return {}
	var items: Dictionary = {}
	for e in _list(state.get("items"), TYPE_ARRAY):
		var item: ItemData = ItemDatabase.get_item(str(e[2])) if e.size() > 2 else null
		var pos: Vector2i = _vec(e)
		if item != null and grid.has(pos):
			items[pos] = item
	var gold: Dictionary = {}
	for e in _list(state.get("gold"), TYPE_ARRAY):
		var pos: Vector2i = _vec(e)
		if e.size() > 2 and int(e[2]) > 0 and grid.has(pos):
			gold[pos] = int(e[2])
	var spotted: Dictionary = {}
	for e in _list(state.get("spotted"), TYPE_ARRAY):
		var pos: Vector2i = _vec(e)
		if grid.get(pos, DungeonState.Tile.WALL) == DungeonState.Tile.TRAP:
			spotted[pos] = true
	var monsters: Array = []
	var taken: Dictionary = {player_pos: true}
	for m in _list(state.get("monsters"), TYPE_DICTIONARY):
		var data: MonsterData = MonsterDatabase.get_monster(str(m.get("id", "")))
		var pos := Vector2i(int(m.get("x", -1)), int(m.get("y", -1)))
		if data == null or taken.has(pos) or grid.get(pos, DungeonState.Tile.WALL) == DungeonState.Tile.WALL:
			continue
		taken[pos] = true
		monsters.append({"data": data, "pos": pos, "hp": int(m.get("hp", 1)), "summoned": bool(m.get("summoned", false))})
	return {
		"width": w, "height": h, "grid": grid, "explored": explored, "stairs": stairs,
		"player": player_pos, "items": items, "gold": gold, "spotted": spotted, "monsters": monsters,
	}

static func _vec(v) -> Vector2i:
	if typeof(v) != TYPE_ARRAY or v.size() < 2:
		return Vector2i(-1, -1)
	return Vector2i(int(v[0]), int(v[1]))

## The entries of a saved list that have the expected type, so one bad entry
## is skipped instead of breaking the whole restore.
static func _list(v, entry_type: int) -> Array:
	var out: Array = []
	if typeof(v) == TYPE_ARRAY:
		for e in v:
			if typeof(e) == entry_type:
				out.append(e)
	return out
