"""16x16 pixel templates. Symbols: O outline, B body, S shade, H highlight,
F face/skin, E eye, A accent, C sash. '.' is transparent."""

GHOST = """
................
.....OOOOOO.....
....OHHBBBBO....
...OHBBBBBBBO...
...OBBBBBBBBO...
...OBEEBBEEBO...
...OBEEBBEEBO...
...OBBBBBBBBO...
...OBBBOOBBBO...
...OBBBBBBBBO...
...OSBBBBBBSO...
...OSBBBBBBSO...
....OSBBBBSSO...
....OSBSBSBSO...
.....OO.OO.OO...
................
"""

DEMON = """
..A..........A..
..AO........OA..
...OOOOOOOOOO...
..OBBBBBBBBBBO..
..OBEEBBBBEEBO..
..OBEEBBBBEEBO..
..OBBBBBBBBBBO..
...OBBOOOOBBO...
....OOBBBBOO....
...OSSBBBBSSO...
..OSBBBBBBBBSO..
.OBOSBBBBBBSOBO.
.OBOSBBBBBBSOBO.
..OO.OSBBSO.OO..
.....OBOOBO.....
....OOO..OOO....
"""

BEAST = """
................
................
..........O.O...
.........OBOBO..
....OOOOOOBBBBO.
...OBBBBBBBBEBBO
..OBBBBBBBBBBBOO
..OBBBBBBBBBBBBA
..OSBBBBBBBBBOO.
..OSBBBBBBBBSO..
...OSSBBBBSSO...
...OBO.OBO.OBO..
...OBO.OBO.OBO..
...OSO.OSO.OSO..
..OOOO.OOO.OOO..
................
"""

ROBED = """
.....OOOOOO.....
....OAAAAAAO....
...OOOOOOOOOO...
....OFFFFFFO....
....OFEFFEFO....
....OFFFFFFO....
.....OFFFFO.....
...OOSBBBBSOO...
..OSBBBBBBBBSO..
..OSBBBBBBBBSO..
.OSBBBBBBBBBBSO.
.OSBBBAABBBBBSO.
.OSBBBAABBBBBSO.
.OSBBBBBBBBBBSO.
.OSSBBBBBBBBSSO.
.OOOOOOOOOOOOOO.
"""

SERPENT = """
................
......OOOO......
.....OBBBBO.....
....OBEBBEBO....
....OBBBBBBO....
.....OOAAOO.....
...OOOBBBBBOOO..
..OBBBBBBBBBBBO.
.OBBSSSSSSSSBBBO
.OBSOOOOOOOOSBBO
.OBSO......OSBBO
.OBSOOOOOOOOSBO.
..OBBSSSSSSBBO..
...OOBBBBBBOO...
.....OOOOOO.....
................
"""

GOLEM = """
................
...OOOOOOOOOO...
..OBBBBBBBBBBO..
..OBEEBBBBEEBO..
..OBBBBBBBBBBO..
..OBBOOOOOOBBO..
.OOBBBBBBBBBBOO.
OBBOSBBBBBBSOBBO
OBBOSBBHHBBSOBBO
OBBOSBBBBBBSOBBO
OSSOSBBBBBBSOSSO
.OOOSBBBBBBSOOO.
...OSBBOOBBSO...
...OBBBOOBBBO...
...OBBBOOBBBO...
..OOOOOOOOOOOO..
"""

HERO = """
.....OOOOOO.....
....OAAAAAAO....
....OAAAAAAO....
....OFFFFFFO....
....OFEFFEFO....
....OFFFFFFO....
.....OOFFOO.....
...OOBBBBBBOO...
..OFOBBBBBBOFO..
..OFOBBBBBBOFO..
..OFOBBCCBBOFO..
...OOBBBBBBOO...
....OSBBBBSO....
....OBBOOBBO....
....OBBOOBBO....
...OOOOOOOOOO...
"""

POTION = """
................
......OOOO......
......OAAO......
.......OO.......
......OBBO......
.....OBBBBO.....
....OBHBBBBO....
....OBHBBBBO....
....OBBBBBBO....
....OBBBBSBO....
....OBBBBSBO....
.....OBBSBO.....
......OOOO......
................
................
................
"""

SCROLL = """
................
..OOOOOOOOOOOO..
.OHHHHHHHHHHHHO.
.OOOOOOOOOOOOOO.
..OFFFFFFFFFFO..
..OFFSSSSSSFFO..
..OFFFFFFFFFFO..
..OFSSSSSSSSFO..
..OFFFFAAFFFFO..
..OFFFFAAFFFFO..
..OFSSSSSSSFFO..
..OFFFFFFFFFFO..
.OOOOOOOOOOOOOO.
.OHHHHHHHHHHHHO.
..OOOOOOOOOOOO..
................
"""

SWORD = """
..............OO
.............OHO
............OHBO
...........OHBO.
..........OHBO..
.........OHBO...
..O.....OHBO....
..OO...OHBO.....
...OOOOHBO......
....OAAOO.......
....OAAO........
...OAOOAO.......
..OAO..OO.......
.OAO............
OAAO............
.OO.............
"""

ARMOR = """
................
..OOO......OOO..
.OBBBO....OBBBO.
.OBHBBOOOOBBBBO.
.OBBBBBBBBBBBBO.
..OBBBBBBBBBBO..
..OBBHBBBBSBBO..
..OBBHBBBBSBBO..
..OBBBBBBBBBBO..
..OBBBBAABBBBO..
...OBBBAABBBO...
...OBBBBBBBBO...
...OSBBBBBBSO...
....OSBBBBSO....
.....OOOOOO.....
................
"""

COIN = """
................
................
.....OOOOOO.....
....OHHBBBBO....
...OHBBBBBBBO...
...OHBBOOBBSO...
...OBBBOBBBSO...
...OBBBOBBBSO...
...OBBBOOBBSO...
...OBBBBBBBSO...
....OBBBBSSO....
.....OOOOOO.....
................
................
................
................
"""

# Gat (Korean brimmed hat): tall crown, accent band, wide brim.
HAT = """
................
................
................
......OOOO......
.....OBBBBO.....
.....OHBBSO.....
.....OHBBSO.....
.....OBBBSO.....
....OAAAAAAO....
.OOOBBBBBBBBOOO.
OHBBBBBBBBBBBBSO
.OSSSSSSSSSSSSO.
..OOOOOOOOOOOO..
................
................
................
"""

# Norigae: cord knot on top, stone in the middle, tassel below.
NORIGAE = """
................
.......OO.......
......OAAO......
......OAAO......
.......OO.......
.....OOBBOO.....
....OBHBBBBO....
....OHBBBBSO....
....OBBBBBSO....
.....OBBBSO.....
......OOOO......
......OAAO......
.....OAAAAO.....
.....OAAAAO.....
.....OAOOAO.....
......O..O......
"""

# Garakji: a band with a stone set on top.
RING = """
................
................
................
......OOOO......
.....OAHAAO.....
......OAAO......
....OOOOOOOO....
...OBHBBBBBBO...
..OBHO....OBBO..
..OBO......OBO..
..OBO......OSO..
..OBO......OSO..
..OBBO....OSSO..
...OBBBBBBSSO...
....OOOOOOOO....
................
"""

# Traditional shoe seen from the side, toe curling up on the right.
SHOES = """
................
................
................
................
................
................
.............OO.
............OAO.
...OOOO....OBAO.
..OBHHBOOOOBBBO.
..OBBBBBBBBBBBO.
.OBBBBBBBBBBBSO.
.OSSSSSSSSSSSSO.
.OAAAAAAAAAAAAO.
..OOOOOOOOOOOO..
................
"""

# Jumeokbap: a triangle of rice wrapped in a band of laver at the bottom.
RICEBALL = """
................
................
................
.......OO.......
......OHBO......
.....OHBBBO.....
.....OHBBBO.....
....OHBBBBBO....
....OBBBBBSO....
...OBBBBBBBSO...
...OAAAAAAAAO...
..OBAAAAAAAASO..
..OSAAAAAAAASO..
..OOOOOOOOOOOO..
................
................
"""

# Gotgam: a flattened dried persimmon with its calyx on top.
PERSIMMON = """
................
................
................
.......AA.......
.....AAAAAA.....
....OOAAAAOO....
...OBHHBBBBBO...
..OBHBBBBBBBSO..
..OBHBBBBBBBSO..
..OBBBBBBBBBSO..
..OBBBBBBBBSSO..
...OBBBBBBSSO...
....OOOOOOOO....
................
................
................
"""

# Sajatbap: a brass bowl heaped with rice.
RICEBOWL = """
................
................
................
......OOOO......
....OOAAAAOO....
...OAAAAAAAAO...
..OAAAAAAAAAAO..
.OOOOOOOOOOOOOO.
.OHBBBBBBBBBBSO.
..OHBBBBBBBBSO..
...OBBBBBBBBO...
....OBBBBBSO....
.....OOOOOO.....
.....OBBBBO.....
....OOOOOOOO....
................
"""
